### PR TITLE
initial a test plan

### PR DESCRIPTION
**Pull request by hakehuang**
Signed-off-by: U-WBIxa22633 <nxa22633@NXL60519.wbi.nxp.com>

this is a template of IEEE 829 test plan. we can start review and add contents based on this

### CODE REVIEW

**Comment by nashif** [comment]
Can you please convert this to RST (restructuredtext)?

**Review by nashif — CHANGES_REQUESTED** [review]
convert to restructuredtext syntax please.

**Comment by hakehuang** [comment]
> Can you please convert this to RST (restructuredtext)?

I will do it.

**Comment by hakehuang** [comment]
@nashif can you have a review for the updated patch?

**Review by nashif — CHANGES_REQUESTED** [review]
Please follow the documentation guidelines here

https://docs.zephyrproject.org/latest/contribute/doc-guidelines.html

**Comment by hakehuang** [comment]
@nashif update style

**Comment by nashif** [comment]
@hakehuang It would be nice to move this under doc and integrate it into the documentation build. Test it with 'make html' in the doc/ directory.

**Comment by hakehuang** [comment]
@nashif  move to doc folder. and below is the make html log
```

Running Sphinx v1.6.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [100%] plans/index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] plans/index
generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/shared/disk/zephyr_project/qm/doc/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in _build/html.

```

**Comment by nashif** [comment]
> U-WBIxa22633 [nxa22633@NXL60519.wbi.nxp.com](mailto:nxa22633@NXL60519.wbi.nxp.com)

Can you please use a real email? Also use this for the commit (Author)

**Comment by nashif** [comment]
You also will need to squash your commits into one commit.

**Comment by nashif** [comment]
@hakehuang please fix the issues reported here:

https://app.shippable.com/github/zephyrproject-rtos/qm/runs/29/1/tests

**Comment by hakehuang** [comment]
squash into one commit. @nashif  please check. Thanks

**Comment by hakehuang** [comment]
@nashif , I update the patch for format checking and I rename the plan as high level plan. please check again thanks.

**Review by nashif — APPROVED** [review]

**Pull request merged**
